# Generated by Django 5.1.3 on 2024-11-25 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='magen_url',
            new_name='imagen_url',
        ),
    ]
